#!/usr/bin/env python3

import json
import sys


def mirror(layer):
    split = len(layer) // 2
    layer = layer[split:] + layer[:split]
    ergodox_rows = [7, 7, 6, 7, 5, 2, 1, 3]
    offset = 0
    for row in ergodox_rows * 2:
        beg, end = offset, offset + row
        layer = layer[:beg] + list(layer[beg:end][::-1]) + layer[end:]
        offset += row
    return layer


with open(sys.argv[1]) as f:
    keymap = json.load(f)
keymap['layers'] = [mirror(layer) for layer in keymap['layers']]
print(json.dumps(keymap, indent=4, sort_keys=True))
